---
name: Checks

on: [ push ]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      # login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # checkout code
      - name: Checkout
        uses: actions/checkout@v2
      # run unit tests
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      # run linter
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
